# 1st version of docker file ,next 2nd
# creating 1st iteration of the docker image  for currencyservice
# use official node.js base image 
FROM node:18

# set up the working directory , where the app code will be copied and run , this dir act as a container

WORKDIR /app 

# copy the package.json files
# if you don't copy the package.json files, your app doesn't know which dependencies/libralies to install
# when we add package.json file , npm install will take this file and install and downlaid node modules , thats where dependencies are listed under /app file

COPY package*.json ./ 

#install npm install for dowloading and installing dependencies as a node module based on package.json file

RUN npm install 

# after installing dep, libraies we have now our app code to be copied into the working directory we created that is /app

COPY . . 

# we need to expose the port on which the app will run inside the container

EXPOSE 7000

# now we need to run the app , for that we need to execute one command that is node service.js, this means it will start the server.js file and app will start running

CMD ["node", "server.js"]
