name: 1. Basic CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
  
  jobs:
    build-currency-service:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout the code
          uses: actions/checkout@v4
      