name: 2-basic CI pipeline-docker image-GHCR
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-currecy-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Print the info about currency service
        run: |
          echo "We are building the first microservice - currencyservice"
          ls -lrta src/currencyservice
          echo "show me the content of package.json file"
          cat src/currencyservice/package.json
      
      - name: setup the docker buildx
        uses: docker/setup-buildx-action@v3

      - name: logs in to the GitHub Container Registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
