# Iteration 5: Simple Multi-Service CI Pipeline
# Learning Focus: Adding second service, basic path filtering
# Building on Iteration 4 fundamentals

name: 5-simple-multi-service-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Global environment variables
env:
  NODE_VERSION: '18'
  GO_VERSION: '1.23'

jobs:
  # Job 1: Build currencyservice (Node.js)
  build_currencyservice:
    runs-on: ubuntu-latest
    
    env:
      SERVICE_NAME: currencyservice
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Print Info
        run: |
          echo "Service: ${{ env.SERVICE_NAME }}"
          echo "Node Version: ${{ env.NODE_VERSION }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
      
      - name: Install dependencies
        run: |
          cd src/${{ env.SERVICE_NAME }}
          npm install
          npm install --save-dev jest
      
      - name: Run tests
        run: |
          cd src/${{ env.SERVICE_NAME }}
          npm test
      
      - name: Build Docker image (main branch only)
        if: github.ref_name == 'main'
        run: |
          cd src/${{ env.SERVICE_NAME }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest .
      
      - name: Login to Docker Hub
        if: github.ref_name == 'main'
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      
      - name: Push Docker image
        if: github.ref_name == 'main'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          echo "✅ Pushed: ${{ env.SERVICE_NAME }}:latest"

  # Job 2: Build productcatalogservice (Go)
  build_productcatalogservice:
    runs-on: ubuntu-latest
    
    env:
      SERVICE_NAME: productcatalogservice
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Print Info
        run: |
          echo "Service: ${{ env.SERVICE_NAME }}"
          echo "Go Version: ${{ env.GO_VERSION }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
      
      - name: Download dependencies
        run: |
          cd src/${{ env.SERVICE_NAME }}
          go mod download
      
      - name: Run tests
        run: |
          cd src/${{ env.SERVICE_NAME }}
          go test -v ./...
      
      - name: Build Docker image (main branch only)
        if: github.ref_name == 'main'
        run: |
          cd src/${{ env.SERVICE_NAME }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest .
      
      - name: Login to Docker Hub
        if: github.ref_name == 'main'
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      
      - name: Push Docker image
        if: github.ref_name == 'main'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          echo "✅ Pushed: ${{ env.SERVICE_NAME }}:latest"